// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web. '
        'Run flutterfire configure to reconfigure.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYSHTC0YuxYsfybI5yo5DadSUKkVx3XFQ',
    appId: '1:356525557420:android:50c2df310e9736cab10109',
    messagingSenderId: '356525557420',
    projectId: 'ajlan-super-app',
    databaseURL: 'https://ajlan-super-app-default-rtdb.firebaseio.com',
    storageBucket: 'ajlan-super-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX8J4HnYoVHAi0bmhuSZBNpZzf3_gswrA',
    appId: '1:356525557420:ios:4dbd44c54bddbe30b10109',
    messagingSenderId: '356525557420',
    projectId: 'ajlan-super-app',
    databaseURL: 'https://ajlan-super-app-default-rtdb.firebaseio.com',
    storageBucket: 'ajlan-super-app.firebasestorage.app',
    iosClientId:
        '356525557420-i7c3i3ol7e54kbtk9m728mfv4gr4ackb.apps.googleusercontent.com',
    iosBundleId: 'com.ajlan.driver',
  );
}
